# Generated by Django 3.2.18 on 2023-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='data',
            field=models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Температура'),
        ),
    ]
