# Generated by Django 3.2.18 on 2023-05-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время измерения'),
        ),
    ]
