# Generated by Django 3.2.18 on 2023-05-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_auto_20230528_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='discription',
            new_name='description',
        ),
    ]
