# Generated by Django 3.2.18 on 2023-05-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_rename_discription_sensor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='data',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Температура'),
        ),
    ]
