# Generated by Django 3.2.18 on 2023-05-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_alter_measurement_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor',
            new_name='measurements',
        ),
    ]
